# Generated by Django 5.2.4 on 2025-07-25 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcribed_txt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voice_1.audioupload')),
            ],
        ),
        migrations.CreateModel(
            name='TextFileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(upload_to='transcription/')),
                ('svaed_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voice_1.transcription')),
            ],
        ),
    ]
