# Generated by Django 5.2.4 on 2025-07-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfilestorage',
            old_name='svaed_at',
            new_name='saved_at',
        ),
        migrations.RemoveField(
            model_name='audioupload',
            name='user',
        ),
    ]
